### ISSUE TITLE
Figure of the paper

### ISSUE THREAD

**Issue by PierreColombo** [neulab/REALSumm#1]
Hello, 
Thanks a lot for your great work :) . I missed your emnlp presentation :( .
Do you plan to update the code for getting the figure 2/4/5 of the paper ? 
Kindest regards,
Pierre

**Comment by manikbhandari** [comment]
Hi, thanks a lot! I'm glad you liked our work.

The code for getting the data for the figures is provided in the notebook [here](https://github.com/neulab/REALSumm/blob/master/analysis/analysis.ipynb). We generated the figures by taking the data in the notebook and using tikz to create the bar graphs.

**Comment by PierreColombo** [comment]
Hello,
I am not sure to find the data for TAC-2008 and TAC-2009?

**Comment by pranavgour** [comment]
Hi Pierre, obtaining TAC data will require applying to NIST as it cannot be redistributed or publicly shared. More information is at https://tac.nist.gov/data/index.html.

**Comment by PierreColombo** [comment]
How are we suppose to submit to the leaderboard then ?

**Comment by pfliu-nlp** [comment]
Hi, Pierre, so far, I think you can  (i) directly send your results together with some metadata (paper title, metric name ...) to us (for example, me: stefanpengfei@gmail.com)
(ii) or you can set up an account here: http://explainaboard.nlpedia.ai/?search=metaeval and add a record by yourself.
