### ISSUE TITLE
Ignored Values

### ISSUE THREAD

**Issue by PierreColombo** [neulab/REALSumm#2]
Hello,
Thanks a lot for your code.
I am trying to reproduce fig 5a. And i see in code https://github.com/neulab/REALSumm/blob/master/analysis/analysis.ipynb that some value can be ignored ? 
Why is that ? Do you have the code to reproduce fig 5.A ?
Best,

**Comment by manikbhandari** [comment]
Hi, while calculating the correlation value (pearson or kendall's tau) if the p-value is greater than 0.05 which implies that it is statistically insignificant, we ignore it. This can be seen in the code [here](https://github.com/neulab/REALSumm/blob/315bee227f3bf25524419e48b18f18940d90d269/analysis/utils.py#L96).

**Comment by PierreColombo** [comment]
Ouaahh ;) 
Many thanks for the super fast reply ! I definitely missed this line ^^.  It makes total sens :)
